Repository boostcampth/boostcamp3_C, pull requests merged in 2019-02, with the labels that each got.

#49 closed #48 FirebaseCrashlytics 추가
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/LiveApplication.kt
  build.gradle
Labels: gradle 관련, 초간단!

#51 closed #44 과거 거래 내역 기능 추가
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/LiveApplication.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/PastTransaction.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailRvAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/res/drawable/rv_header_border.xml
  app/src/main/res/layout/fragment_detail_past_transaction_body_item.xml
  app/src/main/res/layout/fragment_detail_past_transaction_header_item.xml
  app/src/main/res/layout/fragment_detail_past_transation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#45 closed #39 맵 필터 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/api/Api.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapListener.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/res/drawable/ic_map_food_white_24px.xml
  app/src/main/res/drawable/ic_search_white_24dp.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/motion_01_map_backdrop_end.xml
  app/src/main/res/layout/motion_01_map_backdrop_start.xml
  app/src/main/res/layout/motion_01_map_filter_end.xml
  app/src/main/res/layout/motion_01_map_filter_start.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/scene_map_backdrop_01.xml
  app/src/main/res/xml/scene_map_float_btn_01.xml
  build.gradle
Labels: enhancement

#55 closed #37 HomeActivity Backdrop 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/Bookmark.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/BookmarkRecyclerViewAdapter.kt
  app/src/main/res/drawable-hdpi/btn_home_searchbar.png
  app/src/main/res/drawable-mdpi/btn_home_searchbar.png
  app/src/main/res/drawable-xhdpi/btn_home_searchbar.png
  app/src/main/res/drawable-xxhdpi/btn_home_searchbar.png
  app/src/main/res/drawable-xxxhdpi/btn_home_searchbar.png
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/item_bookmark_recyclerview.xml
  app/src/main/res/layout/layout_main_back_drop.xml
  app/src/main/res/layout/main_back_drop.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#54 closed #46 집 조회하기 구현
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/api/Api.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/apiModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/detailModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/mapModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/HouseResponse.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/DetailRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/MapRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/MapRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/BalloonOverlayView.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/HttpResult.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/MapHelper.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/MapHelperImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/MapUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/MapUtilImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/MarkerOverlay.kt
  app/src/main/res/drawable-mdpi/ic_map_marker_24dp.png
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/windows_map_info.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement

#58 #59 Pull request 템플릿 작성
  PULL_REQUEST_TEMPLATE.md
Labels: 초간단!

#62 closed #61 Update README.md
  README.md
Labels: 초간단!

#60 closed #53 Naver Map 연동
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/LiveApplication.kt
  app/src/main/res/layout/activity_map.xml
  build.gradle
Labels: gradle 관련, xml 관련, 초간단!

#77 closed #71 근처 상권 리스트 출력
  app/src/main/java/kr/co/connect/boostcamp/livewhere/api/Api.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/MapRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/MapRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/BackdropMotionLayout.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapListener.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapMarkerAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/dialog_window_map_inifo.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scene_map_backdrop_01.xml
Labels: enhancement

#81 closed #73 detail page 얻은 데이터 처리 (기능 추가)
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/House.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/MarkerInfo.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/PastTransaction.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/RecentPrice.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragmentTransactionMore.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/layout/fragment_detail_past_transaction_more.xml
  app/src/main/res/layout/fragment_detail_recent_price.xml
  app/src/main/res/layout/fragment_detail_trend_price.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#83 Closed #56 검색화면 추가 및 기존 구조 변경
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/appModules.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/bookmarkModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/recentSearchModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/Bookmark.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/RecentSearch.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/BookmarkRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/BookmarkRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/RecentSearchRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/RecentSearchRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivityViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/BookmarkRecyclerViewAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/RecentSearchRecyclerViewAdapter.kt
  app/src/main/res/drawable/ic_arrow_back_white_24dp.xml
  app/src/main/res/drawable/ic_history_black_24dp.xml
  app/src/main/res/drawable/ic_history_white_24dp.xml
  app/src/main/res/drawable/ic_outline_map_white_24px.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_backdrop.xml
  app/src/main/res/layout/fragment_recent_search.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_bookmark_recycler_view.xml
  app/src/main/res/layout/item_recent_search_recycler_view.xml
  app/src/main/res/layout/motion_01_map_backdrop_end.xml
  app/src/main/res/layout/motion_01_map_backdrop_start.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement

#90 closed #89 custom chrome tab으로 상권 url 연결
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVBindingUtil.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/item_place_search_recyclerview.xml
  build.gradle
Labels: enhancement

#92 closed #82 파이어베이스 Realtime database연동 및 리뷰 리스트 조회 기능 추가
  .gitignore
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/detailModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/BaseValueEventListener.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/FirebaseDatabaseRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/FirebaseMapper.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/IMapper.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/ReviewMapper.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/Review.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/entity/ReviewEntity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/DetailRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/ReviewRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragmentReviewMore.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/layout/fragment_detail_review.xml
  app/src/main/res/layout/fragment_detail_review_more.xml
Labels: enhancement

#99 closed #96 맵 내에 중첩 오버레이 개선하기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/LiveApplication.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/OnMarkerListener.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/PlaceImageViewMotionLayout.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement

#104 closed #103 코드 리팩토링
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/HouseInfo.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapMarkerAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/PlaceImageViewMotionLayout.kt
  app/src/main/res/layout/item_house_search_recyclerview.xml
  app/src/main/res/values/strings.xml
Labels: 초간단!

#102 closed #93 거주 경험 코멘트 등록 기능 구현
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/FirebaseDatabaseRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/FirebaseMapper.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/entity/ReviewEntity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragmentReviewMore.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragmentReviewPost.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/adapter/DetailReviewRvAdapter.kt
  app/src/main/res/layout/fragment_detail_post_review.xml
  app/src/main/res/layout/fragment_detail_review.xml
  app/src/main/res/layout/fragment_detail_review_more_item.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#105 closed #97 마커 구조 분리 및 마커 버튼 리스너 등록
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/OnMapHistoryListener.kt
  app/src/main/res/layout/activity_map.xml
Labels: enhancement

#109 closed #95 상권 리사이클러뷰에 대한 기능 추가
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/Address.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/House.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/MarkerInfo.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/res/drawable/ic_park.xml
  app/src/main/res/layout/item_empty_recyclerview.xml
  app/src/main/res/layout/item_house_search_recyclerview.xml
  app/src/main/res/layout/item_place_search_recyclerview.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#110 closed #108 로그인 페이지 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/appModules.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/loginModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/LoginRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/login/LoginActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/login/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_detail_past_transation.xml
  app/src/main/res/layout/fragment_detail_recent_price.xml
  app/src/main/res/layout/fragment_detail_review.xml
  app/src/main/res/layout/fragment_detail_trend_price.xml
  app/src/main/res/layout/fragment_login.xml
  build.gradle
Labels: enhancement

#112 closed #106 상권 검색 리사이클러뷰 기능 관련, UI / UX 변경
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/Address.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/House.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/MarkerInfo.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/OnMapHistoryListener.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/item_house_search_recyclerview.xml
  app/src/main/res/layout/item_place_search_recyclerview.xml
  app/src/main/res/layout/motion_01_map_backdrop_end.xml
  app/src/main/res/layout/motion_01_map_backdrop_start.xml
  app/src/main/res/layout/motion_02_map_backdrop_end.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/scene_map_backdrop_01.xml
Labels: enhancement

#114 closed #111 markerInfo 데이터 전달 및 처리
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/PastTransaction.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/adapter/DetailReviewRvAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/BarChartUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/drawable/ic_bookmark_border_white_24dp.xml
  app/src/main/res/drawable/ic_post_black.xml
  app/src/main/res/drawable/rv_body_border.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_detail_past_transaction_body_item.xml
  app/src/main/res/layout/fragment_detail_past_transaction_more.xml
  app/src/main/res/layout/fragment_detail_past_transation.xml
  app/src/main/res/layout/fragment_detail_post_review.xml
  app/src/main/res/layout/fragment_detail_recent_price.xml
  app/src/main/res/layout/fragment_detail_review.xml
  app/src/main/res/layout/fragment_detail_review_more_item.xml
  app/src/main/res/layout/fragment_detail_trend_price.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#116 closed #113 Map Activity backpressed 막기
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/mapModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/MapRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivityManagerImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/adapter/MapMarkerAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/adapter/MapSearchRVAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/MapActivityManager.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/OnMapHistoryListener.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/OnSearchTrigger.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/view/BackdropMotionLayout.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/view/PlaceImageViewMotionLayout.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/motion_01_map_backdrop_end.xml
  app/src/main/res/layout/motion_01_map_backdrop_start.xml
  app/src/main/res/layout/motion_02_map_backdrop_end.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#118 #117 back pressed 관련 무한 토스트 로직 이슈 제거
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivityManagerImpl.kt
Labels: enhancement

#119 closed #115 detail page pnu코드, building name 처리 및 디자인 적용
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/res/drawable/ic_arrow_downward_black_24dp.xml
  app/src/main/res/drawable/ic_arrow_upward_black_24dp.xml
  app/src/main/res/layout/fragment_detail_past_transaction_more.xml
  app/src/main/res/layout/fragment_detail_post_review.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#122 closed #121 백드롭 성능 이슈 및 버그 문제
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/view/BackdropMotionLayout.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/motion_01_map_backdrop_end.xml
  app/src/main/res/layout/motion_01_map_backdrop_start.xml
  app/src/main/res/layout/motion_01_map_place_image_view_end.xml
  app/src/main/res/layout/motion_01_map_place_image_view_start.xml
  app/src/main/res/layout/motion_02_map_backdrop_end.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/scene_map_backdrop_01.xml
  app/src/main/res/xml/scene_map_place_image_view.xml
Labels: enhancement

#124 closed #123 매물 리사이클러뷰 0개 아이템일 때 오류 문제
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/adapter/MapSearchRVAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/OnMapHistoryListener.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#126 Closed #107 최근검색어, 즐겨찾기 데이터베이스 설계 및 연결
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/data/dao/BookmarkDAO.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/data/dao/RecentSearchDAO.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/data/database/AppDataBase.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/data/entity/BookmarkEntity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/data/entity/RecentSearchEntity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/appModules.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/bookmarkModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/databaseModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/homeModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/recentSearchModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/Bookmark.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/BookmarkRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/BookmarkRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/RecentSearchRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/RecentSearchRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/BookmarkBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/BookmarkViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/BookmarkRecyclerViewAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/RecentSearchRecyclerViewAdapter.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_backdrop.xml
  app/src/main/res/layout/fragment_recent_search.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_bookmark_recycler_view.xml
  app/src/main/res/layout/item_recent_search_recycler_view.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement

#127 closed #125 백드롭 타이틀 관련 기능 추가
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
Labels: 초간단!

#130 closed #129 places 라이브러리 추가
  app/build.gradle
Labels: gradle 관련

#133 closed #131 View 리팩토링
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/mapModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/CameraPositionInfo.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/MapRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivityManagerImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/MapActivityManager.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/OnMapHistoryListener.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/OnSearchTrigger.kt
  app/src/main/res/drawable/ic_cafe.xml
  app/src/main/res/drawable/ic_hospital.xml
  app/src/main/res/drawable/ic_house.xml
  app/src/main/res/drawable/ic_mall.xml
  app/src/main/res/drawable/ic_school.xml
  app/src/main/res/drawable/ic_signboard.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/item_house_search_recyclerview.xml
  app/src/main/res/layout/item_place_search_recyclerview.xml
  app/src/main/res/layout/motion_01_map_backdrop_middle.xml
  app/src/main/res/layout/motion_01_map_backdrop_start.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/scene_map_backdrop_01.xml
Labels: enhancement

#135 closed #132 detail page 북마크 - firebase 추가기능 구현
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/BookmarkUserDatabaseRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/res/drawable/background_detail_imagetext_round_square_black.xml
  app/src/main/res/drawable/ic_bookmark_border_white_24dp.xml
  app/src/main/res/drawable/ic_bookmark_white_24dp.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_detail_image.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#139 closed #136 detail page progressbar 추가
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/res/layout/activity_detail.xml
Labels: enhancement, 초간단!

#137 Closed #84 Google AutoComplete 기능추가
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/appModules.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/searchModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/AutoCompleteRecyclerViewAdapter.kt
  app/src/main/res/layout/fragment_recent_search.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_auto_complete_recycler_view.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#141 closed #134 즐겨찾기 필터 버튼 및 백드롭 속도 변경
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/motion_01_map_backdrop_end.xml
  app/src/main/res/layout/motion_01_map_backdrop_middle.xml
  app/src/main/res/layout/motion_01_map_backdrop_start.xml
  app/src/main/res/xml/scene_map_backdrop_01.xml
  build.gradle
Labels: enhancement

#143 closed #142 건물 사진 관련 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/StreetMapActivity.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/activity_street_map.xml
  app/src/main/res/values/api.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#145 closed #144 map activity, map street activity toolbar 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/StreetMapActivity.kt
  app/src/main/res/drawable/gradient_black_to_transparent.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/activity_street_map.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#147 closed #146 map activity logo 및 scale view 모션레이아웃 변경
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-hdpi/icon_logo.png
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/motion_01_map_backdrop_end.xml
  app/src/main/res/layout/motion_01_map_backdrop_middle.xml
  app/src/main/res/layout/motion_01_map_backdrop_start.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/scene_map_backdrop_01.xml
Labels: enhancement, xml 관련

#150 closed #149 상권 검색시에 0개의 place 리스트시 오류 처리
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
Labels: 초간단!

#152 closed #151 StreetMapActivity 구조 분리
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/mapModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/StreetMapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/StreetMapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/StreetMapViewModel.kt
  app/src/main/res/layout/activity_street_map.xml
Labels: enhancement

#157 closed #148 넘어온 latlng 값을 통해서 초기 지도 구축 및 백드롭 개선
  app/src/main/java/kr/co/connect/boostcamp/livewhere/api/Api.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/MapRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/MapRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/PassTouchRecyclerView.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/StreetMapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/OnMapHistoryListener.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/view/BackdropMotionLayout.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/motion_01_map_backdrop_end.xml
  app/src/main/res/layout/motion_01_map_backdrop_middle.xml
  app/src/main/res/layout/motion_01_map_backdrop_start.xml
  app/src/main/res/xml/scene_map_backdrop_01.xml
Labels: enhancement

#159 closed #158 Update README.md
  README.md
Labels: 초간단!

#161 closed #160 map page UI 수정
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/OnMapHistoryListener.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/view/BackdropMotionLayout.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/item_place_search_recyclerview.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#167 closed #164 ui 변경 및 코드 정리
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/PassTouchRecyclerView.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/StreetMapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/adapter/MapSearchRVAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/OnViewHistoryListener.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/HttpResult.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/item_place_search_recyclerview.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#168 closed #166 detail review 등록/ 시세추이 버튼 UI 개선
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragmentReviewPost.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/KeyboardUtil.kt
  app/src/main/res/drawable/background_detail_trend_price_button_active.xml
  app/src/main/res/drawable/background_detail_trend_price_button_inactive.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_detail_post_review.xml
  app/src/main/res/layout/fragment_detail_trend_price.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, xml 관련

#170 Closed #155 UI 편집 및 오류 수정
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/appModules.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/bookmarkModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/homeModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/searchModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/BookmarkRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/BookmarkRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/RecentSearchRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/RecentSearchRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/BookmarkViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/AutoCompleteRecyclerViewAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/BookmarkRecyclerViewAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/RecentSearchRecyclerViewAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_backdrop.xml
  app/src/main/res/layout/fragment_recent_search.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_auto_complete_recycler_view.xml
  app/src/main/res/layout/item_bookmark_recycler_view.xml
  app/src/main/res/layout/item_recent_search_recycler_view.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#174 Closed #172 BookmarkRepository Refactoring
  app/src/main/java/kr/co/connect/boostcamp/livewhere/data/dao/BookmarkDAO.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/data/dao/RecentSearchDAO.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/BookmarkRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/BookmarkRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/RecentSearchRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/AutoCompleteRecyclerViewAdapter.kt
  app/src/main/res/layout/activity_home.xml
Labels: enhancement

#177 closed #173 map activity, recyclerview 버그 및 클릭 이슈
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/mapModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/adapter/MapSearchRVAdapter.kt
  app/src/main/res/drawable/ic_search_navigation_24dp.xml
  app/src/main/res/drawable/ic_search_site_24dp.xml
  app/src/main/res/layout/item_empty_recyclerview.xml
  app/src/main/res/layout/item_house_search_recyclerview.xml
  app/src/main/res/layout/item_place_search_recyclerview.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#175 closed #169 Detail page 이미지 클릭 스트리트뷰 이동 , 차트 예외처리
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/appModules.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/detailModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/BookmarkRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/BookmarkRecyclerViewAdapter.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#180 closed #179 아이템 관련 UI / UX 및 클릭 리스너 제거
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/item_house_search_recyclerview.xml
  app/src/main/res/layout/item_place_search_recyclerview.xml
Labels: enhancement

#182 closed #181 MapViewModel 구조 분리 및 리팩토링
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/adapter/MapSearchRVAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/interfaces/MapActivityManager.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/view/PassTouchRecyclerView.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/view/PlaceImageViewMotionLayout.kt
  app/src/main/res/layout/activity_map.xml
Labels: enhancement

#183 closed #178 local - remote database 동기화 및 emptyList 표현 처리
  app/src/main/java/kr/co/connect/boostcamp/livewhere/data/dao/BookmarkDAO.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/BookmarkRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_detail_image.xml
  app/src/main/res/layout/fragment_detail_review.xml
  app/src/main/res/layout/fragment_detail_review_more.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#186 closed #184 검색 리스트를 누를 경우에 맵 반응
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/item_house_search_recyclerview.xml
  app/src/main/res/layout/item_place_search_recyclerview.xml
Labels: enhancement

#176 Closed #171 검색시 정확도 향상
  app/src/main/java/kr/co/connect/boostcamp/livewhere/api/TmapApi.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/data/entity/BookmarkEntity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/data/entity/RecentSearchEntity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/apiModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/appModules.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/homeModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/Poi.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/TmapPoi.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/TmapPois.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/TmapResponse.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/AutoCompleteRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/AutoCompleteRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/RecentSearchRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_bookmark_recycler_view.xml
  fia
Labels: enhancement

#188 closed #187 map activity에서 비어있는 아이템일 경우 lottie 처리
  app/build.gradle
  app/src/main/assets/crying_animation.json
  app/src/main/res/layout/item_empty_recyclerview.xml
  app/src/main/res/values/dimens.xml
  build.gradle
Labels: enhancement

#193 closed #192 HomeActivity로 온 위경도 값을 통해서 MapActivity 검색
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
Labels: enhancement

#194 closed #185 detail page progressbar lottie로 변경
  app/src/main/assets/loading_animation.json
  app/src/main/assets/loading_animation2.json
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_detail_image.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#197 closed #196 상권 리스트를 통해서 마커로 이동할 경우, infowindow가 사라지지 않는 현상
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVBindingUtil.kt
Labels: enhancement

#199 Closed #191 UI 오류 수정
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/api/TmapApi.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/apiModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/AutoCompleteRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/AutoCompleteRepositoryImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchBindingUtil.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_recent_search_recycler_view.xml
  app/src/main/res/values/colors.xml
  build.gradle
Labels: enhancement

#200 closde #195 barchart 수직 선 삭제
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/BarChartUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
Labels: enhancement

#204 closed #201 Map내의 각종 프로그레스 처리
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/HttpResult.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#205 closed #202 Detail page progressBar,줄간격,review 삭제 이슈 처리
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/ReviewDatabaseRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragmentReviewMore.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/adapter/DetailReviewRvAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/drawable/ic_delete_black_24dp.xml
  app/src/main/res/layout/fragment_detail_review.xml
  app/src/main/res/layout/fragment_detail_review_more_item.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#207 closed #203 에러 수정 및 중복 클릭 방지
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SearchBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/BookmarkRecyclerViewAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/adapter/RecentSearchRecyclerViewAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/drawable/shape_cursor.xml
  app/src/main/res/layout/fragment_recent_search.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_bookmark_recycler_view.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#206 closed #198 움직이는 마커를 통한 매물 검색
  app/src/main/assets/marker.json
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/res/drawable-mdpi/ic_marker.png
  app/src/main/res/drawable/ic_close_white_24dp.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/motion_01_map_backdrop_middle.xml
  app/src/main/res/layout/motion_01_map_backdrop_start.xml
  app/src/main/res/layout/motion_01_map_search_btn_end.xml
  app/src/main/res/layout/motion_01_map_search_btn_start.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/scene_map_search_btn_01.xml
Labels: enhancement

#212 closed #208 스트리트뷰 열기 중복 클릭 방지
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/StreetView.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragmentReviewMore.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/res/layout/fragment_detail_image.xml
Labels: enhancement

#210 closed #209 백드롭과 리스트가 타이틀이 집의 이름이 나오도록 변경
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapSearchRVBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/res/layout/item_house_search_recyclerview.xml
Labels: enhancement

#213 Closed #211 RecyclerView Multitouch Block
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeViewModel.kt
Labels: enhancement

#216 closed #214 마커가 없어지는 버그와 매물 검색 취소를 누를 경우 리스트 값 변경
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/motion_01_map_search_btn_end.xml
  app/src/main/res/layout/motion_01_map_search_btn_start.xml
Labels: enhancement

#217 closed #215 firebase bookmark 데이터베이스 용도 변경
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/res/layout/fragment_detail_image.xml
Labels: enhancement

#218 Closed #190 Splash Theme 추가
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-hdpi/splash_logo.png
  app/src/main/res/drawable-mdpi/splash_logo.png
  app/src/main/res/drawable-xhdpi/splash_logo.png
  app/src/main/res/drawable-xxhdpi/splash_logo.png
  app/src/main/res/drawable-xxxhdpi/splash_logo.png
  app/src/main/res/drawable/ic_search_black_24dp.xml
  app/src/main/res/drawable/img_splash.png
  app/src/main/res/layout/item_recent_search_recycler_view.xml
  app/src/main/res/xml/splash_background.xml
Labels: 초간단!

#220 closed #219 코드 정리
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/BookmarkUserDatabaseRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/BookmarkUserMapper.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/FirebaseMapper.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/firebase/ReviewDatabaseRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragmentReviewPost.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragmentTransactionMore.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/adapter/DetailTransactionRvAdapter.kt
Labels: enhancement

#222 #221 중복 클릭 방지 프래그먼트 전환시 재 실행 이슈 해결
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragment.kt
Labels: enhancement

#224 closed #223 android9(Pie)버전 street view 대응
  app/src/main/AndroidManifest.xml
Labels: bug

#226 closed #225 검색을 취소하고, 다시 상권 검색시에 매물 찾기가 되는 버그 방지
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
Labels: enhancement, 초간단!

#228 closed #227 개인정보 권한 넣기
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/PolicyFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_policy.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/values/terms_of_use.xml
Labels: enhancement

#232 closed #231 Map 관련 버그
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
Labels: enhancement
