Repository boostcampth/boostcamp3_C, pull requests merged in 2019-01, with the labels that each got.

#3 closed #2 기능별 패키지 분리 및 gradle버전 최신화
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  build.gradle
Labels: enhancement

#10 closed #5 프로젝트 기본 구조 만들기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/LiveApplication.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/api/Api.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/apiModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/appModules.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/detailModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/repository/DetailRepository.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/BaseViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_detail.xml
  build.gradle
Labels: enhancement

#13 closed #9 Tmap 지도 연동하기
  app/build.gradle
  app/libs/com.skt.Tmap_1.58.jar
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/appModules.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/mapModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/MapHelper.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/MapHelperImpl.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/MapUtilImpl.kt
  app/src/main/res/layout/activity_map.xml
  build.gradle
Labels: enhancement

#16 closed #14 HomeActivity UI 수정 및 Style 추가
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivityViewModel.kt
  app/src/main/res/drawable-hdpi/btn_home_search_bar.png
  app/src/main/res/drawable-hdpi/img_all_arrow_up_black.png
  app/src/main/res/drawable-hdpi/img_all_arrow_up_white.png
  app/src/main/res/drawable-hdpi/img_home_logo.png
  app/src/main/res/drawable-hdpi/img_map_cafe.png
  app/src/main/res/drawable-hdpi/img_map_food.png
  app/src/main/res/drawable-hdpi/img_map_hospital.png
  app/src/main/res/drawable-hdpi/img_map_school.png
  app/src/main/res/drawable-hdpi/img_map_store.png
  app/src/main/res/drawable-hdpi/shape_drop_bar_main.xml
  app/src/main/res/drawable-mdpi/btn_home_search_bar.png
  app/src/main/res/drawable-mdpi/img_all_arrow_up_black.png
  app/src/main/res/drawable-mdpi/img_all_arrow_up_white.png
  app/src/main/res/drawable-mdpi/img_home_logo.png
  app/src/main/res/drawable-mdpi/img_map_cafe.png
  app/src/main/res/drawable-mdpi/img_map_food.png
  app/src/main/res/drawable-mdpi/img_map_hospital.png
  app/src/main/res/drawable-mdpi/img_map_school.png
  app/src/main/res/drawable-mdpi/img_map_store.png
  app/src/main/res/drawable-xhdpi/btn_home_search_bar.png
  app/src/main/res/drawable-xhdpi/img_all_arrow_up_black.png
  app/src/main/res/drawable-xhdpi/img_all_arrow_up_white.png
  app/src/main/res/drawable-xhdpi/img_home_logo.png
  app/src/main/res/drawable-xhdpi/img_map_cafe.png
  app/src/main/res/drawable-xhdpi/img_map_food.png
  app/src/main/res/drawable-xhdpi/img_map_hospital.png
  app/src/main/res/drawable-xhdpi/img_map_school.png
  app/src/main/res/drawable-xhdpi/img_map_store.png
  app/src/main/res/drawable-xxhdpi/btn_home_search_bar.png
  app/src/main/res/drawable-xxhdpi/img_all_arrow_up_black.png
  app/src/main/res/drawable-xxhdpi/img_all_arrow_up_white.png
  app/src/main/res/drawable-xxhdpi/img_home_logo.png
  app/src/main/res/drawable-xxhdpi/img_map_cafe.png
  app/src/main/res/drawable-xxhdpi/img_map_food.png
  app/src/main/res/drawable-xxhdpi/img_map_hospital.png
  app/src/main/res/drawable-xxhdpi/img_map_school.png
  app/src/main/res/drawable-xxhdpi/img_map_store.png
  app/src/main/res/drawable-xxxhdpi/btn_home_search_bar.png
  app/src/main/res/drawable-xxxhdpi/img_all_arrow_up_black.png
  app/src/main/res/drawable-xxxhdpi/img_all_arrow_up_white.png
  app/src/main/res/drawable-xxxhdpi/img_home_logo.png
  app/src/main/res/drawable-xxxhdpi/img_map_cafe.png
  app/src/main/res/drawable-xxxhdpi/img_map_food.png
  app/src/main/res/drawable-xxxhdpi/img_map_hospital.png
  app/src/main/res/drawable-xxxhdpi/img_map_school.png
  app/src/main/res/drawable-xxxhdpi/img_map_store.png
  app/src/main/res/drawable/shape_drop_bar_white.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#23 closed #21 keystore.properties 추가
  .gitignore
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/di/apiModule.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/map/MapBindingAdapter.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: enhancement

#26 closed #25 Firebase gradle 추가
  app/build.gradle
  app/src/main/res/layout/activity_home.xml
  build.gradle
Labels: enhancement

#33 closed #32 서울살이 ui 제목 변경
  app/src/main/AndroidManifest.xml
  docs/ui/seoul42_ui.png
Labels: 초간단!

#34 1/30 Dev branch Readme파일 수정
  README.md
Labels: 초간단!

#29 closed #27 detail페이지 view,layout 작업
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailActivity.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_detail_image.xml
  app/src/main/res/layout/fragment_detail_past_transation.xml
  app/src/main/res/layout/fragment_detail_recent_price.xml
  app/src/main/res/layout/fragment_detail_review.xml
  app/src/main/res/layout/fragment_detail_trend_price.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, xml 관련

#40 closed #35 MpAndroidChart추가 및 UI 구성
  app/build.gradle
  app/src/main/java/kr/co/connect/boostcamp/livewhere/model/HouseAvgPrice.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/BarChartUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/layout/fragment_detail_trend_price.xml
  app/src/main/res/values/dimens.xml
  build.gradle
Labels: enhancement

#38 closed #36 백드롭 리스너 드래그에서 클릭으로 변경
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/MapHelperImpl.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/xml/scene_map_backdrop_01.xml
Labels: xml 관련, 초간단!

#42 Update README.md
  README.md
Labels: 초간단!

#43 closed #41 detail page 이미지 데이터 가져오기
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailBindingUtil.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/detail/DetailViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/util/ConstVal.kt
  app/src/main/res/layout/fragment_detail_image.xml
  app/src/main/res/layout/fragment_detail_trend_price.xml
Labels: enhancement

#47 closed #19 Splash 화면 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivity.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/HomeActivityViewModel.kt
  app/src/main/java/kr/co/connect/boostcamp/livewhere/ui/main/SplashActivity.kt
  app/src/main/res/drawable/shape_drop_bar_main.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/item_bookmark_recyclerview.xml
  app/src/main/res/layout/layout_splash.xml
  app/src/main/res/layout/main_back_drop.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/splash_background.xml
Labels: enhancement
